### Hello world
http://localhost:8000/

### Greet
http://localhost:8000/greet/Malik/malik
### Greet with ignored parameter
http://localhost:8000/greets/Malik/ignored/City

### Greet
POST http://localhost:8000/task
Content-Type: application/json

{
    "id": 4,
    "name": "Malik"
}

### blocking task
http://localhost:8000/blocking_task

### serve static files
http://localhost:8000/static/index.html

### forwarding request based on path
http://localhost:8000/forwarding/sum/1/2
### forwarding request based on path
http://localhost:8000/forwarding/sum/3three/4four