[package]
name = "warp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.7"
pretty_env_logger = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4","serde"] }
rand = "0.8"